### PR TITLE
Fix pointer math.

### LINKED ISSUE #120910: libc-test panic: `unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false`
libc-test now panics since `1.78.0-nightly (d44e3b95c 2024-02-09)`.

### Code

repo: https://github.com/rust-lang/libc
example GHA run: https://github.com/rust-lang/libc/actions/runs/7852817358/job/21431727248

Not minimized yet.

```shell
gh repo clone rust-lang/libc
cd libc/libc-test
cargo test
```

### Meta

`rustc --version --verbose`:
```
rust version 1.78.0-nightly (d44e3b95c 2024-02-09)
```

### Error output

```
  thread 'main' panicked at library/core/src/panicking.rs:155:5:
  unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread caused non-unwinding panic. aborting.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jsirois**
The previous use of `get_unchecked` was UB according to
https://doc.rust-lang.org/nightly/std/primitive.slice.html#safety-2
and https://github.com/rust-lang/rust/pull/120594 exposed this leading
to a panic caught by tests as:
```
cargo test --all
...
thread 'fold::tests::ident_transformation_in_defs' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: hint::assert_unchecked must never be called when the condition is false
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p garando_syntax --lib`
...
```

Fixes https://github.com/rust-lang/rust/issues/120910

### CODE REVIEW

File: garando_syntax/src/util/move_map.rs [hunk 1]
```diff
@@ -29,13 +29,13 @@ impl<T> MoveMap<T> for Vec<T> {
             while read_i < old_len {
                 // move the read_i'th item out of the vector and map it
                 // to an iterator
-                let e = ptr::read(self.get_unchecked(read_i));
+                let e = ptr::read(self.as_mut_ptr().offset(read_i as isize));
```
Comment (jsirois) [inline garando_syntax/src/util/move_map.rs:32]: I did not comment these casts but I'm a noob to this sort of manipulation in Rust.

My reading of https://doc.rust-lang.org/reference/type-layout.html#primitive-data-layout, though, particularly "usize and isize have a size big enough to contain every address on the target platform.", seems to suggest this is always OK.

**Review by JohnTitor — APPROVED** [review]
Thanks!

**Comment by ehuss** [comment]
@JohnTitor Would it be possible to get a new release of garando_syntax with this change?

It seems like there are some other unreleased changes, like https://github.com/JohnTitor/garando/commit/5c993dfa986ecf1e0a09cff5ad9b5c7bbed2cfef, which is a semver breakage and might also require a new version of ctest2?
